#include "audiomanager.h"

/*!
 * \brief PortAudioCallback
 * See documentation here: https://portaudio.com/docs/v19-doxydocs/writing_a_callback.html
 * \param input And
 * \param output are either arrays of interleaved samples or;
 * if non-interleaved samples were requested using the paNonInterleaved sample format flag,
 * an array of buffer pointers, one non-interleaved buffer for each channel
 * \param frameCount Number of sample frames to be processed by the stream callback
 * \param timeInfo Timestamps for the first sample in the input buffer, the output time for the first sample in the output buffer,
 * and the time the callback was invoked
 * \param statusFlags Whether input and/or output buffers have been inserted or will be dropped to overcome underflow oder overflow conditions
 * \param userData A pointer to a user supplied data structure for storing additional data
 * \return The stream callback should return one of the values in the PaStreamCallbackResult enumeration.
 * To ensure that the callback continues to be called, it should return paContinue (0).
 * Either paComplete or paAbort can be returned to finish stream processing, after either of these values is returned the callback will not be called again.
 * If paAbort is returned the stream will finish as soon as possible.
 * If paComplete is returned, the stream will continue until all buffers generated by the callback have been played.
 * This may be useful in applications such as soundfile players where a specific duration of output is required.
 * However, it is not necessary to utilize this mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also be used to stop the stream.
 * The callback must always fill the entire output buffer irrespective of its return value.
 */
static int PortAudioCallback(const void *inputBuffer, void *outputBuffer,
                             unsigned long framesPerBuffer,
                             const PaStreamCallbackTimeInfo* timeInfo,
                             PaStreamCallbackFlags statusFlags,
                             void *userData)
{
    QTime currentTime = QTime::currentTime();
    qInfo() << "Timestamp: " << currentTime.toString("hh:mm:ss:zzz");
    return 0;
}

namespace
{
    void ConfigurePaStreamParameters(std::shared_ptr<PaStreamParameters> parameters,
                                     int channelCount, PaDeviceIndex deviceIndex, PaSampleFormat sampleFormat,
                                     PaMacCoreStreamInfo& coreAudioInfo)
    {
        // ToDo: Fill parameter with zeros ???
        parameters->channelCount = channelCount;
        parameters->device = deviceIndex;
        parameters->sampleFormat = sampleFormat;
        parameters->hostApiSpecificStreamInfo = NULL;

        PaMacCore_SetupStreamInfo(&coreAudioInfo, paMacCorePro);
        parameters->hostApiSpecificStreamInfo = &coreAudioInfo;

        parameters->suggestedLatency = 0.001;
    }

    void LogAudioDeviceInformation(int amountOfAudioDevices)
    {
        for(int i = 0; i <= (amountOfAudioDevices - 1); i++)
        {
            auto deviceInfo = Pa_GetDeviceInfo(i);

            qInfo() << "Device " << i;
            qInfo() << "Name: " << deviceInfo->name;
            qInfo() << "Max. output channels: " << deviceInfo->maxOutputChannels;
            qInfo() << "Max. input channels: " << deviceInfo->maxInputChannels;
            qInfo() << "Default sample rate: " << deviceInfo->defaultSampleRate;
        }
    }
}


struct AudioManager::Impl
{
    bool audiofault = {false};
    bool soundIsRunning = {false};

    int amountOfAudioDevices = {-1};
    /// Anzahl der Samples, die jedesmal generiert werden
    int frameSize = {512};
    /// 48 kHz
    int sampleRate = {48000};
    int audioChannels = {1};
    unsigned short bufferSize = {0};

    PaError portAudioError;

    PaSampleFormat sampleFormat = {paInt16};

    std::shared_ptr<CallbackData> additionalData = {std::make_shared<CallbackData>()};

    std::shared_ptr<PaStreamParameters> inputParameters = {std::make_shared<PaStreamParameters>()};
    std::shared_ptr<PaStreamParameters> outputParameters = {std::make_shared<PaStreamParameters>()};

    PaStream* stream;

    Impl(){}
};

AudioManager::AudioManager(QObject *parent)
    : QObject{parent}
    , m(std::make_shared<Impl>())
{ }

AudioManager::~AudioManager()
{
    if(m->soundIsRunning)
    {
        m->portAudioError = Pa_CloseStream(m->stream);
        if(m->portAudioError == paNoError)
        {
            m->soundIsRunning = false;
        }
    }
}

/// Je kleiner die frameSize (also der audio buffer),desto kleiner die Latenz, ABER desto höher die Wahrscheinlichkeit für Audio-Dropouts.
/// Das unterscheidet sich von System zu System -> ausprobieren!
bool AudioManager::Initialize(int frameSize, int sampleRate, int audioChannels)
{
    InitPortAudio();
    if(m->portAudioError != paNoError) return false;

    m->frameSize = frameSize;
    m->sampleRate = sampleRate;
    m->audioChannels = audioChannels;
    m->bufferSize = m->frameSize * m->audioChannels * 2;

    LogAudioDeviceInformation(m->amountOfAudioDevices);
    ConfigureAudioDevice();
    qDebug() << "Successfully initialized.";
    return true;
}

void AudioManager::Run()
{
    qDebug() << "Running ...";
    // https://files.portaudio.com/docs/v19-doxydocs/portaudio_8h.html#a443ad16338191af364e3be988014cbbe
    m->portAudioError = Pa_OpenStream(&(m->stream),
                                    m->inputParameters.get(),
                                    m->outputParameters.get(),
                                    m->sampleRate,
                                    m->frameSize,
                                    paClipOff,
                                    PortAudioCallback,
                                    m->additionalData.get());

    if(m->portAudioError == paNoError)
    {
        m->audiofault = false;
        qDebug() << "Starting Stream ...";
        m->portAudioError = Pa_StartStream(m->stream);
        if(m->portAudioError == paNoError)
        {
            qInfo() << "Sound running ...";
            m->soundIsRunning = true;
        }
        else
        {
            qInfo() << "Sound not running.";
            m->soundIsRunning = false;
        }
    }
    else
    {
        m->audiofault = true;
        m->soundIsRunning = false;
        qWarning() << "Audiofault.";
    }


    // ToDo: Combine with Client to send Data to server
    // neue sendslotdata und client aufrufen oder audiomanager erstellt sich selber einen client hier
    // pastream stückeln Größe der Pakete?
}


/// Catch all initial problems that could lead to a failed run
void AudioManager::InitPortAudio()
{
    m->portAudioError = Pa_Initialize();

    if(m->portAudioError != paNoError)
    {
        qWarning() << "Could not initialize PortAudio.";
    }

    m->amountOfAudioDevices = Pa_GetDeviceCount();

    if(m->amountOfAudioDevices < 0)
    {
        qWarning() << "ERROR: Number of Devices came back negative with " << m->amountOfAudioDevices;
    }
}

void AudioManager::ConfigureAudioDevice()
{
    /// Configure input parameters
    static PaMacCoreStreamInfo coreAudioInputInfo;
    ConfigurePaStreamParameters(m->inputParameters, m->audioChannels, 2, paInt16, coreAudioInputInfo);

    /// Configure output parameters
    static PaMacCoreStreamInfo coreAudioOutputInfo;
    ConfigurePaStreamParameters(m->outputParameters, m->audioChannels, 3, paInt16, coreAudioOutputInfo);
}






