#include "portAudioCallback.h"


///// ENCODING RELATED BEGIN
#include "QObject"
#include <QDebug>
#include "opus.h"
#include "opus_custom.h"
#include "opus_types.h"
#include "utils.h"

int opusError{};
OpusCustomMode *opusMode   = opus_custom_mode_create(48000, 512, &opusError);
OpusCustomEncoder *encoder = opus_custom_encoder_create(opusMode, 1, &opusError);
OpusCustomDecoder *decoder = opus_custom_decoder_create(opusMode, 1, &opusError);

unsigned char *encodedAudioData = new unsigned char[1024];
short *decodedAudioData = new short[1024];
int length = 128;

#include <iostream>
using namespace std;
///// ENCODING RELATED END




/// The "callback" is a function that is called by the PortAudio engine whenever it has captured audio data, or when it needs more audio data for output.
/*!
 * \brief PortAudioCallback
 * See documentation here: https://portaudio.com/docs/v19-doxydocs/writing_a_callback.html
 * \param inputBuffer And
 * \param outputBuffer are either arrays of interleaved samples or;
 * if non-interleaved samples were requested using the paNonInterleaved sample format flag,
 * an array of buffer pointers, one non-interleaved buffer for each channel
 * \param framesPerBuffer Number of sample frames to be processed by the stream callback
 * \param timeInfo Timestamps for the first sample in the input buffer, the output time for the first sample in the output buffer,
 * and the time the callback was invoked
 * \param statusFlags Whether input and/or output buffers have been inserted or will be dropped to overcome underflow oder overflow conditions
 * \param userData A pointer to a user supplied data structure for storing additional data
 * \return The stream callback should return one of the values in the PaStreamCallbackResult enumeration.
 * To ensure that the callback continues to be called, it should return paContinue (0).
 * Either paComplete or paAbort can be returned to finish stream processing, after either of these values is returned the callback will not be called again.
 * If paAbort is returned the stream will finish as soon as possible.
 * If paComplete is returned, the stream will continue until all buffers generated by the callback have been played.
 * This may be useful in applications such as soundfile players where a specific duration of output is required.
 * However, it is not necessary to utilize this mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also be used to stop the stream.
 * The callback must always fill the entire output buffer irrespective of its return value.
 */
int PortAudioCallback(const void *inputBuffer,
                            void *outputBuffer,
                            unsigned long framesPerBuffer,
                            [[maybe_unused]] const PaStreamCallbackTimeInfo* timeInfo,
                            [[maybe_unused]] PaStreamCallbackFlags statusFlags,
                            void *userData)
{
    auto input = static_cast<const char *> (inputBuffer);
    const auto output = static_cast<char *>(outputBuffer);

    const auto pCallbackData = static_cast<CallbackData *>(userData);
	const bool clientfault = pCallbackData->pAudioManager->GetClientfault();
    // Input- und Outputbuffer definieren

	if(clientfault){
    // input direkt in den output schreiben
		qDebug() << "Client fault";
    	for (unsigned int i=0; i < framesPerBuffer * 2; i++)
    	{
        	output[i] = input[i];
    	}
	}
	else
	{
		auto spAudioData = std::make_shared<QByteArray>(input, framesPerBuffer *2);

		// encode input and send to server
		pCallbackData->pAudioManager->ProcessAudioInput(spAudioData);


		// Get received data from buffer
		std::shared_ptr<QByteArray> spReceivedData;
		bool success = pCallbackData->pAudioManager->GetReceivedAudioData(spReceivedData);

		if (success)
		{
			const auto receivedData = spReceivedData->data();

			/// ENCODING AND DECODING OF RECEIVED AUDIO BUFFER
			int reduceQualityBy = 1;

			int length = opus_custom_encode(encoder, (short *) receivedData, framesPerBuffer, encodedAudioData, 128/reduceQualityBy);
                        cout << "ENCODING RESULT: " << length << endl;
  			int samples = opus_custom_decode(decoder, encodedAudioData, 128/reduceQualityBy, decodedAudioData, framesPerBuffer);
                        cout << "DECODING RESULT: " << samples << endl;

			char* decodedAudioDataAsChar =  (char *) decodedAudioData;
		        /// END OF EN- AND DECODING

			for (unsigned int i=0; i < framesPerBuffer * 2; i++)
			{
				output[i] = decodedAudioDataAsChar[i];
				//output[i] = receivedData[i];
			}
		}
	}
    return 0;
}
