#include "portAudioCallback.h"

/// The "callback" is a function that is called by the PortAudio engine whenever it has captured audio data, or when it needs more audio data for output.
/*!
 * \brief PortAudioCallback
 * See documentation here: https://portaudio.com/docs/v19-doxydocs/writing_a_callback.html
 * \param inputBuffer And
 * \param outputBuffer are either arrays of interleaved samples or;
 * if non-interleaved samples were requested using the paNonInterleaved sample format flag,
 * an array of buffer pointers, one non-interleaved buffer for each channel
 * \param framesPerBuffer Number of sample frames to be processed by the stream callback
 * \param timeInfo Timestamps for the first sample in the input buffer, the output time for the first sample in the output buffer,
 * and the time the callback was invoked
 * \param statusFlags Whether input and/or output buffers have been inserted or will be dropped to overcome underflow oder overflow conditions
 * \param userData A pointer to a user supplied data structure for storing additional data
 * \return The stream callback should return one of the values in the PaStreamCallbackResult enumeration.
 * To ensure that the callback continues to be called, it should return paContinue (0).
 * Either paComplete or paAbort can be returned to finish stream processing, after either of these values is returned the callback will not be called again.
 * If paAbort is returned the stream will finish as soon as possible.
 * If paComplete is returned, the stream will continue until all buffers generated by the callback have been played.
 * This may be useful in applications such as soundfile players where a specific duration of output is required.
 * However, it is not necessary to utilize this mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also be used to stop the stream.
 * The callback must always fill the entire output buffer irrespective of its return value.
 */
int PortAudioCallback(const void *inputBuffer,
                            void *outputBuffer,
                            unsigned long framesPerBuffer,
                            [[maybe_unused]] const PaStreamCallbackTimeInfo* timeInfo,
                            [[maybe_unused]] PaStreamCallbackFlags statusFlags,
                            void *userData)
{
    const auto pCallbackData = static_cast<CallbackData *>(userData);

    // Input- und Outputbuffer definieren
    auto input = static_cast<const char *> (inputBuffer);
    const auto output = static_cast<char *>(outputBuffer);

    auto spAudioData = std::make_shared<QByteArray>(input, framesPerBuffer *2);
    //qDebug() << "PortAudioCallback: Input Buffer size:" << spAudioData->size();
    // encode input and send to server
    pCallbackData->pAudioManager->ProcessAudioInput(spAudioData);

    // input direkt in den output schreiben
    for (unsigned int i=0; i < framesPerBuffer * 2; i++)
    {
        //output[i] = input[i];
    }

    // Get received data from buffer
    std::shared_ptr<QByteArray> spReceivedData;
    bool success = pCallbackData->pAudioManager->GetReceivedAudioData(spReceivedData);

    if (success)
    {
        const auto receivedData = spReceivedData->data();
        //const auto receivedSize = spReceivedData->size();
        for (unsigned int i=0; i < framesPerBuffer * 2; i++)
        {
            output[i] = receivedData[i];
            //output[i] += receivedData[i];
        }
    }

    //qDebug() << "Output Inhalt: " << *output;
    return 0;
}
