#include "../../include/portaudio-snapshot/include/portaudio.h"
#include "callbackdata.h"

/*!
 * \brief PortAudioCallback
 * See documentation here: https://portaudio.com/docs/v19-doxydocs/writing_a_callback.html
 * \param input And
 * \param output Are either arrays of interleaved samples or;
 * if non-interleaved samples were requested using the paNonInterleaved sample format flag,
 * an array of buffer pointers, one non-interleaved buffer for each channel
 * \param frameCount Number of sample frames to be processed by the stream callback
 * \param timeInfo Timestamps for the first sample in the input buffer, the output time for the first sample in the output buffer,
 * and the time the callback was invoked
 * \param statusFlags Whether input and/or output buffers have been inserted or will be dropped to overcome underflow oder overflow conditions
 * \param userData A pointer to a user supplied data structure for storing additional data
 * \return The stream callback should return one of the values in the PaStreamCallbackResult enumeration.
 * To ensure that the callback continues to be called, it should return paContinue (0).
 * Either paComplete or paAbort can be returned to finish stream processing, after either of these values is returned the callback will not be called again.
 * If paAbort is returned the stream will finish as soon as possible.
 * If paComplete is returned, the stream will continue until all buffers generated by the callback have been played.
 * This may be useful in applications such as soundfile players where a specific duration of output is required.
 * However, it is not necessary to utilize this mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also be used to stop the stream.
 * The callback must always fill the entire output buffer irrespective of its return value.
 */
static int PortAudioCallback(const void* input, void* output,
                             unsigned long frameCount,
                             const PaStreamCallbackTimeInfo timeInfo,
                             PaStreamCallbackFlags statusFlags,
                             void* userData)
{

}
