#include "portAudioCallback.h"

/// The "callback" is a function that is called by the PortAudio engine whenever it has captured audio data, or when it needs more audio data for output.
/*!
 * \brief PortAudioCallback
 * See documentation here: https://portaudio.com/docs/v19-doxydocs/writing_a_callback.html
 * \param inputBuffer And
 * \param outputBuffer are either arrays of interleaved samples or;
 * if non-interleaved samples were requested using the paNonInterleaved sample format flag,
 * an array of buffer pointers, one non-interleaved buffer for each channel
 * \param framesPerBuffer Number of sample frames to be processed by the stream callback
 * \param timeInfo Timestamps for the first sample in the input buffer, the output time for the first sample in the output buffer,
 * and the time the callback was invoked
 * \param statusFlags Whether input and/or output buffers have been inserted or will be dropped to overcome underflow oder overflow conditions
 * \param userData A pointer to a user supplied data structure for storing additional data
 * \return The stream callback should return one of the values in the PaStreamCallbackResult enumeration.
 * To ensure that the callback continues to be called, it should return paContinue (0).
 * Either paComplete or paAbort can be returned to finish stream processing, after either of these values is returned the callback will not be called again.
 * If paAbort is returned the stream will finish as soon as possible.
 * If paComplete is returned, the stream will continue until all buffers generated by the callback have been played.
 * This may be useful in applications such as soundfile players where a specific duration of output is required.
 * However, it is not necessary to utilize this mechanism as Pa_StopStream(), Pa_AbortStream() or Pa_CloseStream() can also be used to stop the stream.
 * The callback must always fill the entire output buffer irrespective of its return value.
 */
int PortAudioCallback(const void *inputBuffer,
                            void *outputBuffer,
                            unsigned long framesPerBuffer,
                            [[maybe_unused]] const PaStreamCallbackTimeInfo* timeInfo,
                            [[maybe_unused]] PaStreamCallbackFlags statusFlags,
                            void *userData)
{
    const auto pCallbackData = static_cast<CallbackData *>(userData);
    qDebug() << "PortAudioCallback: Input Buffer size, framesPerBuffer:" << sizeof(&inputBuffer) << ", " << framesPerBuffer;
    // Input- und Outputbuffer definieren
    auto input = static_cast<const char *> (inputBuffer);
    const auto output = static_cast<char *>(outputBuffer);

    //encoder action
    const int maxLength = framesPerBuffer*4; //1276 scheint grade max in der praxis bei framesperbuffer 512
    const int frameSize = 512;
    const int sampleRate = 48000;
    const int channels = 1;
    int err;
    opus_int16 *decodedData = new opus_int16[frameSize*channels*sizeof(opus_int16)]();
    const opus_int16* inputForOpus = reinterpret_cast<const opus_int16 *> (input); //Length of "array": framesPerBuffer?
    unsigned char* encoded = new unsigned char[maxLength]();

    /*
    auto mode = opus_custom_mode_create(sampleRate, frameSize, &err);
    OpusCustomEncoder *encoder = opus_custom_encoder_create(mode, channels, &err);
    if(err != OPUS_OK) qDebug() << "PortAudioCallback: OpusCustomEncoder creation failed: " << err;
    int length = opus_custom_encode(encoder, inputForOpus, frameSize, encoded, maxLength);
    if(length < 0) qDebug() << "PortAudioCallback: OpusCustomEncoder failed encoding: " << length;
    else qDebug() << "Encoded To A Length Of Bytes: " << length;
    opus_custom_encoder_destroy(encoder);
    //int length = pCallbackData->pAudioManager->EncodeWithOpus(inputForOpus, encoded); //TODO: Sent length to server
    const char* encodedConst = reinterpret_cast<const char*> (encoded);
    //TODO: instead of create/destroy reset? opus_custom_encoder_ctl(encoder, OPUS_RESET_STATE)
    // Doc says: Do not re-initialize for every frame
    //decoder action
    int lengthToDecode = length; //TODO: get real length from server
    OpusCustomDecoder *decoder = opus_custom_decoder_create(mode, channels, &err);
    if(err != OPUS_OK) qDebug() << "PortAudioCallback: OpusCustomDecoder creation failed: " << err;
    int samples = opus_custom_decode(decoder, encodedConst, lengthToDecode, decodedData, frameSize); //samples should be framesize?
    if(samples < 0) qDebug() << "PortAudioCallback: OpusCustomDecoder failed decoding: " << samples;
    else qDebug() << "Decoded samples: " << samples;
    const char* decodedConst = reinterpret_cast<const char*> (decodedData);
    opus_custom_decoder_destroy(decoder);
    */

    //Not custom encoder
    OpusEncoder *encoder = opus_encoder_create(sampleRate, channels, OPUS_APPLICATION_VOIP, err);
    if(err != OPUS_OK) qDebug() << "PortAudioCallback: OpusEncoder creation failed: " << err;
    opus_int32 length = opus_encode(encoder, inputForOpus, framesPerBuffer, encoded, maxLength);
    if(length < 0) qDebug() << "PortAudioCallback: OpusEncoder failed encoding: " << length;
    else qDebug() << "Encoded To A Length Of Bytes: " << length;
    OpusDecoder *decoder = opus_decoder_create(sampleRate, channels, err);
    if(err != OPUS_OK) qDebug() << "PortAudioCallback: OpusDecoder creation failed: " << err;
    int samples = opus_decode(decoder, encoded, length, decodedData, framesPerBuffer, 0); //flag if error correction data is decoded
    if(samples < 0) qDebug() << "PortAudioCallback: OpusDecoder failed decoding: " << samples;
    else qDebug() << "Decoded samples: " << samples;
    // send input to server
    auto spAudioData = std::make_shared<QByteArray>(encodedConst, length);
    pCallbackData->pAudioManager->SendAudioInputToServer(spAudioData);

    // input direkt in den output schreiben
    for (unsigned int i=0; i < framesPerBuffer * 2; i++)
    {
        //output[i] = input[i];
    }

    // Get received data from buffer
    std::shared_ptr<QByteArray> spReceivedData;
    bool success = pCallbackData->pAudioManager->GetReceivedAudioData(spReceivedData);

    if (success)
    {
        const auto receivedData = spReceivedData->data();
        //const auto receivedSize = spReceivedData->size();
        //auto decodedData = pCallbackData->pAudioManager->DecodeWithOpus(spReceivedData, lengthToDecode);

        for (unsigned int i=0; i < samples * 2; i++)
        {
            output[i] = decodedConst[i];
            //output[i] += decodedConst[i];
            //qDebug() << "Output: " << output[i] << " " << input[i];
        }
    }

    //qDebug() << "Output Inhalt: " << *output;
    opus_custom_mode_destroy(mode);
    return 0;
}
